### ISSUE TITLE
Could not load graphics?

### ISSUE THREAD

**Issue by KevinTyrrell** [raxod502/TerraFrame#11]
https://i.imgur.com/vK4cg3s.png

Seems the project does not know about the textures folder?

**Comment by lucasnpereira** [comment]
It seems you have to run it from the textures folder as the working folder.

**Comment by KevinTyrrell** [comment]
No luck with that either: 

https://i.imgur.com/OCNDYYi.png

**Comment by lucasnpereira** [comment]
you have to point your class path to the folder were the .class files are

**Comment by jchama** [comment]
Just to keep up with all this mess move all the texture subfolders to the src folder :)

**Comment by KevinTyrrell** [comment]
@jchama That worked. Thanks. 

@lucasnpereira How is that done? Usually I use an IDE to manage my project structure so I'm not familiar with it.

**Comment by KevinTyrrell** [comment]
Not moving the character is normal right? Character just drops from the sky and after that, no user input is read?

**Comment by raxod502** [comment]
Check up on the man-pages of `javac` and `java`; it's quite enlightening to learn how the tools work without an IDE. You can compile and run with:

```
$ mkdir -p out
$ javac -d out src/*.java
$ java -cp out:textures TerrariaClone
```

For fixing errors, see #12 and https://github.com/BusyByte/TerraFrame/pull/1, but note that I'm not personally involved in the development of either.

**Comment by sirtawast** [comment]
@raxod502 maybe add these compile instructions to readme.md 🤔

**Comment by moonpatroller** [comment]
That would be nice. :|

**Comment by raxod502** [comment]
Done in https://github.com/raxod502/TerrariaClone/commit/3a792f8cbd39ef4e139516fbdefec3dd66d1eb36.

**Comment by jmarucha** [comment]
compile instructions don't work on windows, w/a is copying textures to `out` and running `java TerrariaClone`
this is a great game

**Comment by raxod502** [comment]
Maybe Windows uses a different delimiter for the classpath. I wouldn't put it past them.
