### ISSUE TITLE
delet this

### ISSUE THREAD

**Issue by JuanPotato** [raxod502/TerraFrame#5]
please

**Comment by raxod502** [comment]
It's out of my hands at this point, unfortunately.

**Comment by JuanPotato** [comment]
think of the children D:

**Comment by raxod502** [comment]
You may want to switch to this fork: https://github.com/raxod502/TerraFrame/pull/4

**Comment by JuanPotato** [comment]
That guy is the best optimizer I've seen.

**Comment by voidnull000** [comment]
please delete this still tho
