### ISSUE TITLE
Revert Boxing Fix Commit

### ISSUE THREAD

**Issue by Restioson** [raxod502/TerraFrame#6]
[This](https://github.com/raxod502/TerraFrame/commit/0dab089fc90b0d8bf1ee6a78bfca22317bd39e56) commit should be reverted. It stands in the way of the glorious code from which our lord and savior, the Flying Spaghetti Monster, was created.

**Comment by raxod502** [comment]
Good point.

**Comment by voidnull000** [comment]
give the spaget

**Comment by Restioson** [comment]
no
